from . import employee_promotion
from . import hr_employee
from . import promotion_type
from . import promotion_approved
from . import promotion_popup
from . import internal_vacancy
from . import applications
from . import ceo_approved
from . import promotion_minutes